spring:
  liquibase:
    change-log: classpath:liquibase.xml
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#       ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
  freemarker:
    suffix: .ftl








